# PART - 1 - Data Cleaning and Feature Engineering

In [1]:
import pandas as pd

## read csv files of world happiness report dataset 2020, 2021, and 2022

In [2]:
y22 = pd.read_csv('2022.csv')
y22

,RANK,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,1,Finland,"7,821","7,886","7,756","2,518","1,892","1,258","0,775","0,736","0,109","0,534"
1,2,Denmark,"7,636","7,710","7,563","2,226","1,953","1,243","0,777","0,719","0,188","0,532"
2,3,Iceland,"7,557","7,651","7,464","2,320","1,936","1,320","0,803","0,718","0,270","0,191"
3,4,Switzerland,"7,512","7,586","7,437","2,153","2,026","1,226","0,822","0,677","0,147","0,461"
4,5,Netherlands,"7,415","7,471","7,359","2,137","1,945","1,206","0,787","0,651","0,271","0,419"
...,...,...,...,...,...,...,...,...,...,...,...,...
142,143,Rwanda*,"3,268","3,462","3,074","0,536","0,785","0,133","0,462","0,621","0,187","0,544"
143,144,Zimbabwe,"2,995","3,110","2,880","0,548","0,947","0,690","0,270","0,329","0,106","0,105"
144,145,Lebanon,"2,955","3,049","2,862","0,216","1,392","0,498","0,631","0,103","0,082","0,034"
145,146,Afghanistan,"2,404","2,469","2,339","1,263","0,758","0,000","0,289","0,000","0,089","0,005"
146,147,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
y21 = pd.read_csv('2021.csv')
y21

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.700,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800
145,Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648
146,Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095
147,Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205
148,Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [4]:
y20 = pd.read_csv('2020.csv')
y20

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Central African Republic,Sub-Saharan Africa,3.4759,0.115183,3.701658,3.250141,6.625160,0.319460,45.200001,0.640881,0.082410,0.891807,1.972317,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,2.860198
149,Rwanda,Sub-Saharan Africa,3.3123,0.052425,3.415053,3.209547,7.600104,0.540835,61.098846,0.900589,0.055484,0.183541,1.972317,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,0.548445
150,Zimbabwe,Sub-Saharan Africa,3.2992,0.058674,3.414202,3.184198,7.865712,0.763093,55.617260,0.711458,-0.072064,0.810237,1.972317,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,0.841031
151,South Sudan,Sub-Saharan Africa,2.8166,0.107610,3.027516,2.605684,7.425360,0.553707,51.000000,0.451314,0.016519,0.763417,1.972317,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,1.378751
152,Afghanistan,South Asia,2.5669,0.031311,2.628270,2.505530,7.462861,0.470367,52.590000,0.396573,-0.096429,0.933687,1.972317,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,1.507236

## working on 2022 dataset

In [5]:
y22.columns

Index(['RANK', 'Country', 'Happiness score', 'Whisker-high', 'Whisker-low',
       'Dystopia (1.83) + residual', 'Explained by: GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption'],
      dtype='object')

In [6]:
#check NaN
y22.isnull().sum()

RANK                                          0
Country                                       0
Happiness score                               1
Whisker-high                                  1
Whisker-low                                   1
Dystopia (1.83) + residual                    1
Explained by: GDP per capita                  1
Explained by: Social support                  1
Explained by: Healthy life expectancy         1
Explained by: Freedom to make life choices    1
Explained by: Generosity                      1
Explained by: Perceptions of corruption       1
dtype: int64

In [7]:
#drop NaN
y22 = y22.dropna()
y22

,RANK,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,1,Finland,"7,821","7,886","7,756","2,518","1,892","1,258","0,775","0,736","0,109","0,534"
1,2,Denmark,"7,636","7,710","7,563","2,226","1,953","1,243","0,777","0,719","0,188","0,532"
2,3,Iceland,"7,557","7,651","7,464","2,320","1,936","1,320","0,803","0,718","0,270","0,191"
3,4,Switzerland,"7,512","7,586","7,437","2,153","2,026","1,226","0,822","0,677","0,147","0,461"
4,5,Netherlands,"7,415","7,471","7,359","2,137","1,945","1,206","0,787","0,651","0,271","0,419"
...,...,...,...,...,...,...,...,...,...,...,...,...
141,142,Botswana*,"3,471","3,667","3,275","0,187","1,503","0,815","0,280","0,571","0,012","0,102"
142,143,Rwanda*,"3,268","3,462","3,074","0,536","0,785","0,133","0,462","0,621","0,187","0,544"
143,144,Zimbabwe,"2,995","3,110","2,880","0,548","0,947","0,690","0,270","0,329","0,106","0,105"
144,145,Lebanon,"2,955","3,049","2,862","0,216","1,392","0,498","0,631","0,103","0,082","0,034"
145,146,Afghanistan,"2,404","2,469","2,339","1,263","0,758","0,000","0,289","0,000","0,089","0,005"

In [8]:
#check again
y22.isnull().sum()

RANK                                          0
Country                                       0
Happiness score                               0
Whisker-high                                  0
Whisker-low                                   0
Dystopia (1.83) + residual                    0
Explained by: GDP per capita                  0
Explained by: Social support                  0
Explained by: Healthy life expectancy         0
Explained by: Freedom to make life choices    0
Explained by: Generosity                      0
Explained by: Perceptions of corruption       0
dtype: int64

In [9]:
# clear unwated string
y22 = y22[~y22['Country'].str.contains('\*')]
y22

,RANK,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,1,Finland,"7,821","7,886","7,756","2,518","1,892","1,258","0,775","0,736","0,109","0,534"
1,2,Denmark,"7,636","7,710","7,563","2,226","1,953","1,243","0,777","0,719","0,188","0,532"
2,3,Iceland,"7,557","7,651","7,464","2,320","1,936","1,320","0,803","0,718","0,270","0,191"
3,4,Switzerland,"7,512","7,586","7,437","2,153","2,026","1,226","0,822","0,677","0,147","0,461"
4,5,Netherlands,"7,415","7,471","7,359","2,137","1,945","1,206","0,787","0,651","0,271","0,419"
...,...,...,...,...,...,...,...,...,...,...,...,...
138,139,Tanzania,"3,702","3,847","3,558","0,735","0,848","0,597","0,425","0,578","0,248","0,270"
139,140,Sierra Leone,"3,574","3,732","3,416","1,556","0,686","0,416","0,273","0,387","0,202","0,055"
143,144,Zimbabwe,"2,995","3,110","2,880","0,548","0,947","0,690","0,270","0,329","0,106","0,105"
144,145,Lebanon,"2,955","3,049","2,862","0,216","1,392","0,498","0,631","0,103","0,082","0,034"
145,146,Afghanistan,"2,404","2,469","2,339","1,263","0,758","0,000","0,289","0,000","0,089","0,005"

In [10]:
# replace string for better undersanding
y22 = y22.replace(',', '.', regex=True)
y22

,RANK,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,1,Finland,7.821,7.886,7.756,2.518,1.892,1.258,0.775,0.736,0.109,0.534
1,2,Denmark,7.636,7.710,7.563,2.226,1.953,1.243,0.777,0.719,0.188,0.532
2,3,Iceland,7.557,7.651,7.464,2.320,1.936,1.320,0.803,0.718,0.270,0.191
3,4,Switzerland,7.512,7.586,7.437,2.153,2.026,1.226,0.822,0.677,0.147,0.461
4,5,Netherlands,7.415,7.471,7.359,2.137,1.945,1.206,0.787,0.651,0.271,0.419
...,...,...,...,...,...,...,...,...,...,...,...,...
138,139,Tanzania,3.702,3.847,3.558,0.735,0.848,0.597,0.425,0.578,0.248,0.270
139,140,Sierra Leone,3.574,3.732,3.416,1.556,0.686,0.416,0.273,0.387,0.202,0.055
143,144,Zimbabwe,2.995,3.110,2.880,0.548,0.947,0.690,0.270,0.329,0.106,0.105
144,145,Lebanon,2.955,3.049,2.862,0.216,1.392,0.498,0.631,0.103,0.082,0.034
145,146,Afghanistan,2.404,2.469,2.339,1.263,0.758,0.000,0.289,0.000,0.089,0.005

In [11]:
y22 = y22.replace('Czechia', 'Czech Republic', regex=True)
y22

,RANK,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,1,Finland,7.821,7.886,7.756,2.518,1.892,1.258,0.775,0.736,0.109,0.534
1,2,Denmark,7.636,7.710,7.563,2.226,1.953,1.243,0.777,0.719,0.188,0.532
2,3,Iceland,7.557,7.651,7.464,2.320,1.936,1.320,0.803,0.718,0.270,0.191
3,4,Switzerland,7.512,7.586,7.437,2.153,2.026,1.226,0.822,0.677,0.147,0.461
4,5,Netherlands,7.415,7.471,7.359,2.137,1.945,1.206,0.787,0.651,0.271,0.419
...,...,...,...,...,...,...,...,...,...,...,...,...
138,139,Tanzania,3.702,3.847,3.558,0.735,0.848,0.597,0.425,0.578,0.248,0.270
139,140,Sierra Leone,3.574,3.732,3.416,1.556,0.686,0.416,0.273,0.387,0.202,0.055
143,144,Zimbabwe,2.995,3.110,2.880,0.548,0.947,0.690,0.270,0.329,0.106,0.105
144,145,Lebanon,2.955,3.049,2.862,0.216,1.392,0.498,0.631,0.103,0.082,0.034
145,146,Afghanistan,2.404,2.469,2.339,1.263,0.758,0.000,0.289,0.000,0.089,0.005

In [12]:
# add Regional indicator in 2022 file

In [13]:
#check the Regional indicator columns in 2021 flie
unique_regional = y21['Regional indicator'].unique()
unique_regional

array(['Western Europe', 'North America and ANZ',
       'Middle East and North Africa', 'Latin America and Caribbean',
       'Central and Eastern Europe', 'East Asia', 'Southeast Asia',
       'Commonwealth of Independent States', 'Sub-Saharan Africa',
       'South Asia'], dtype=object)

In [14]:
y21_region=y21[['Country name', 'Regional indicator']]
print(y21_region)

    Country name  Regional indicator
0        Finland      Western Europe
1        Denmark      Western Europe
2    Switzerland      Western Europe
3        Iceland      Western Europe
4    Netherlands      Western Europe
..           ...                 ...
144      Lesotho  Sub-Saharan Africa
145     Botswana  Sub-Saharan Africa
146       Rwanda  Sub-Saharan Africa
147     Zimbabwe  Sub-Saharan Africa
148  Afghanistan          South Asia

[149 rows x 2 columns]

In [15]:
# group the dataframe by regional indicator
grouped = y21_region.groupby('Regional indicator')

# print the group lists
for name, group in grouped:
    print(name)
    print(group['Country name'].tolist())
    print()

Central and Eastern Europe
['Czech Republic', 'Slovenia', 'Kosovo', 'Slovakia', 'Lithuania', 'Estonia', 'Poland', 'Romania', 'Serbia', 'Latvia', 'Hungary', 'Croatia', 'Bosnia and Herzegovina', 'Montenegro', 'Bulgaria', 'Albania', 'North Macedonia']

Commonwealth of Independent States
['Uzbekistan', 'Kazakhstan', 'Moldova', 'Kyrgyzstan', 'Belarus', 'Russia', 'Tajikistan', 'Armenia', 'Azerbaijan', 'Turkmenistan', 'Georgia', 'Ukraine']

East Asia
['Taiwan Province of China', 'Japan', 'South Korea', 'Mongolia', 'Hong Kong S.A.R. of China', 'China']

Latin America and Caribbean
['Costa Rica', 'Guatemala', 'Uruguay', 'Brazil', 'Mexico', 'Jamaica', 'Panama', 'Chile', 'El Salvador', 'Colombia', 'Nicaragua', 'Argentina', 'Honduras', 'Peru', 'Ecuador', 'Bolivia', 'Paraguay', 'Dominican Republic', 'Venezuela', 'Haiti']

Middle East and North Africa
['Israel', 'Bahrain', 'United Arab Emirates', 'Saudi Arabia', 'Kuwait', 'Libya', 'Turkey', 'Morocco', 'Algeria', 'Iraq', 'Iran', 'Tunisia', 'Lebanon', 'Palestinian Territories', 'Jordan', 'Egypt', 'Yemen']

North America and ANZ
['New Zealand', 'Australia', 'Canada', 'United States']

South Asia
['Nepal', 'Maldives', 'Bangladesh', 'Pakistan', 'Sri Lanka', 'India', 'Afghanistan']

Southeast Asia
['Singapore', 'Thailand', 'Philippines', 'Vietnam', 'Malaysia', 'Indonesia', 'Laos', 'Cambodia', 'Myanmar']

Sub-Saharan Africa
['Mauritius', 'Congo (Brazzaville)', 'Ivory Coast', 'Cameroon', 'Senegal', 'Ghana', 'Niger', 'Gambia', 'Benin', 'Guinea', 'South Africa', 'Gabon', 'Burkina Faso', 'Mozambique', 'Nigeria', 'Mali', 'Uganda', 'Liberia', 'Kenya', 'Namibia', 'Chad', 'Swaziland', 'Comoros', 'Ethiopia', 'Mauritania', 'Madagascar', 'Togo', 'Zambia', 'Sierra Leone', 'Burundi', 'Tanzania', 'Malawi', 'Lesotho', 'Botswana', 'Rwanda', 'Zimbabwe']

Western Europe
['Finland', 'Denmark', 'Switzerland', 'Iceland', 'Netherlands', 'Norway', 'Sweden', 'Luxembourg', 'Austria', 'Germany', 'Ireland', 'United Kingdom', 'Belgium', 'France', 'Malta', 'Spain', 'Italy', 'Cyprus', 'Portugal', 'Greece', 'North Cyprus']

In [16]:
## add the necessary colum
# define the dictionary of country_regions from above informations
country_regions = {
    'Western Europe': ['Finland', 'Denmark', 'Switzerland', 'Iceland', 'Netherlands', 'Norway', 'Sweden', 'Luxembourg', 'Austria', 'Germany', 'Ireland', 'United Kingdom', 'Malta', 'Cyprus', 'Greece', 'Portugal', 'North Cyprus', 'Belgium', 'France', 'Spain', 'Italy'],
    'North America and ANZ': ['New Zealand', 'Australia', 'Canada', 'United States'],
    'Middle East and North Africa': ['Egypt','Israel', 'Bahrain', 'United Arab Emirates', 'Saudi Arabia', 'Kuwait', 'Libya', 'Morocco', 'Palestinian Territories', 'Iraq', 'Lebanon', 'Jordan', 'Tunisia', 'Yemen', 'Iran', 'Algeria', 'Turkey','Armenia'],
    'Central and Eastern Europe': ['Czech Republic','Tajikistan','Czech Republic', 'Slovenia', 'Kosovo', 'Slovakia', 'Lithuania', 'Estonia', 'Poland', 'Kazakhstan', 'Romania', 'Serbia', 'Latvia', 'Bosnia and Herzegovina', 'Moldova', 'Croatia', 'North Macedonia', 'Albania', 'Georgia', 'Ukraine', 'Hungary', 'Uzbekistan', 'Kyrgyzstan', 'Montenegro', 'Bulgaria', 'Russia'],
    'Latin America and Caribbean': ['Costa Rica', 'Guatemala', 'Uruguay', 'Jamaica', 'El Salvador', 'Colombia', 'Nicaragua', 'Argentina', 'Honduras', 'Peru', 'Bolivia', 'Paraguay', 'Dominican Republic', 'Venezuela', 'Haiti', 'Panama', 'Brazil', 'Chile', 'Mexico', 'Ecuador'],
    'Southeast Asia': ['Singapore', 'Thailand', 'Philippines', 'Vietnam', 'Malaysia', 'Indonesia', 'Laos', 'Cambodia', 'Myanmar'],
    'South Asia':['Nepal', 'Maldives', 'Bangladesh', 'Pakistan', 'Sri Lanka', 'India', 'Afghanistan'],
    'East Asia': ['Taiwan Province of China', 'Japan', 'Hong Kong S.A.R. of China', 'South Korea', 'Mongolia','China'],
    'Sub-Saharan Africa': ['Congo','Mauritius', 'Congo (Brazzaville)', 'Ivory Coast', 'Cameroon', 'Senegal', 'Ghana', 'Niger', 'Gambia', 'Benin', 'South Africa', 'Mozambique', 'Nigeria', 'Mali', 'Uganda', 'Liberia', 'Kenya', 'Namibia', 'Madagascar', 'Togo', 'Zambia', 'Sierra Leone', 'Burundi', 'Tanzania', 'Malawi', 'Lesotho', 'Botswana', 'Rwanda', 'Zimbabwe', 'Swaziland', 'Comoros', 'Ethiopia', 'Mauritania', 'Gabon', 'Guinea', 'Burkina Faso'],
}

#add the condition to match the countries and regions. 
def get_region(country):
    for region, countries in country_regions.items():
        if country in countries:
            return region
    return None

# add the new column "Regional Indicator" in 2022 file
y22.insert(2, 'Regional indicator', y22['Country'].apply(get_region))
y22

,RANK,Country,Regional indicator,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,1,Finland,Western Europe,7.821,7.886,7.756,2.518,1.892,1.258,0.775,0.736,0.109,0.534
1,2,Denmark,Western Europe,7.636,7.710,7.563,2.226,1.953,1.243,0.777,0.719,0.188,0.532
2,3,Iceland,Western Europe,7.557,7.651,7.464,2.320,1.936,1.320,0.803,0.718,0.270,0.191
3,4,Switzerland,Western Europe,7.512,7.586,7.437,2.153,2.026,1.226,0.822,0.677,0.147,0.461
4,5,Netherlands,Western Europe,7.415,7.471,7.359,2.137,1.945,1.206,0.787,0.651,0.271,0.419
...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,139,Tanzania,Sub-Saharan Africa,3.702,3.847,3.558,0.735,0.848,0.597,0.425,0.578,0.248,0.270
139,140,Sierra Leone,Sub-Saharan Africa,3.574,3.732,3.416,1.556,0.686,0.416,0.273,0.387,0.202,0.055
143,144,Zimbabwe,Sub-Saharan Africa,2.995,3.110,2.880,0.548,0.947,0.690,0.270,0.329,0.106,0.105
144,145,Lebanon,Middle East and North Africa,2.955,3.049,2.862,0.216,1.392,0.498,0.631,0.103,0.082,0.034
145,146,Afghanistan,South Asia,2.404,2.469,2.339,1.263,0.758,0.000,0.289,0.000,0.089,0.005

In [17]:
y21.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

In [18]:
y22.columns

Index(['RANK', 'Country', 'Regional indicator', 'Happiness score',
       'Whisker-high', 'Whisker-low', 'Dystopia (1.83) + residual',
       'Explained by: GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption'],
      dtype='object')

In [19]:
#change the colums name to match with 2021 file
y22 = y22.rename(columns={'Country': 'Country name','Explained by: GDP per capita':'Log GDP per capita', 'Explained by: Social support':'Social support',
       'Explained by: Healthy life expectancy':'Healthy life expectancy',
       'Explained by: Freedom to make life choices':'Freedom to make life choices',
       'Explained by: Generosity':'Generosity', 'Explained by: Perceptions of corruption': 'Perceptions of corruption','Dystopia (1.83) + residual':'Dystopia + residual'})
y22

,RANK,Country name,Regional indicator,Happiness score,Whisker-high,Whisker-low,Dystopia + residual,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,Western Europe,7.821,7.886,7.756,2.518,1.892,1.258,0.775,0.736,0.109,0.534
1,2,Denmark,Western Europe,7.636,7.710,7.563,2.226,1.953,1.243,0.777,0.719,0.188,0.532
2,3,Iceland,Western Europe,7.557,7.651,7.464,2.320,1.936,1.320,0.803,0.718,0.270,0.191
3,4,Switzerland,Western Europe,7.512,7.586,7.437,2.153,2.026,1.226,0.822,0.677,0.147,0.461
4,5,Netherlands,Western Europe,7.415,7.471,7.359,2.137,1.945,1.206,0.787,0.651,0.271,0.419
...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,139,Tanzania,Sub-Saharan Africa,3.702,3.847,3.558,0.735,0.848,0.597,0.425,0.578,0.248,0.270
139,140,Sierra Leone,Sub-Saharan Africa,3.574,3.732,3.416,1.556,0.686,0.416,0.273,0.387,0.202,0.055
143,144,Zimbabwe,Sub-Saharan Africa,2.995,3.110,2.880,0.548,0.947,0.690,0.270,0.329,0.106,0.105
144,145,Lebanon,Middle East and North Africa,2.955,3.049,2.862,0.216,1.392,0.498,0.631,0.103,0.082,0.034
145,146,Afghanistan,South Asia,2.404,2.469,2.339,1.263,0.758,0.000,0.289,0.000,0.089,0.005

In [20]:
# Add Year colums to be easy to diffirentciate after marging the flies
y22.insert(loc=0, column='Year', value=2022)
y22

,Year,RANK,Country name,Regional indicator,Happiness score,Whisker-high,Whisker-low,Dystopia + residual,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,2022,1,Finland,Western Europe,7.821,7.886,7.756,2.518,1.892,1.258,0.775,0.736,0.109,0.534
1,2022,2,Denmark,Western Europe,7.636,7.710,7.563,2.226,1.953,1.243,0.777,0.719,0.188,0.532
2,2022,3,Iceland,Western Europe,7.557,7.651,7.464,2.320,1.936,1.320,0.803,0.718,0.270,0.191
3,2022,4,Switzerland,Western Europe,7.512,7.586,7.437,2.153,2.026,1.226,0.822,0.677,0.147,0.461
4,2022,5,Netherlands,Western Europe,7.415,7.471,7.359,2.137,1.945,1.206,0.787,0.651,0.271,0.419
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,2022,139,Tanzania,Sub-Saharan Africa,3.702,3.847,3.558,0.735,0.848,0.597,0.425,0.578,0.248,0.270
139,2022,140,Sierra Leone,Sub-Saharan Africa,3.574,3.732,3.416,1.556,0.686,0.416,0.273,0.387,0.202,0.055
143,2022,144,Zimbabwe,Sub-Saharan Africa,2.995,3.110,2.880,0.548,0.947,0.690,0.270,0.329,0.106,0.105
144,2022,145,Lebanon,Middle East and North Africa,2.955,3.049,2.862,0.216,1.392,0.498,0.631,0.103,0.082,0.034
145,2022,146,Afghanistan,South Asia,2.404,2.469,2.339,1.263,0.758,0.000,0.289,0.000,0.089,0.005

In [21]:
# check if there are any misssing values
y22.isnull().sum()

Year                            0
RANK                            0
Country name                    0
Regional indicator              0
Happiness score                 0
Whisker-high                    0
Whisker-low                     0
Dystopia + residual             0
Log GDP per capita              0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

In [22]:
# saving a new 2022 dataframe to csv 
y22.to_csv('new2022.csv',index=False)

In [23]:
# Read saved file and to cheack 
new2022 = pd.read_csv('new2022.csv')
new2022

,Year,RANK,Country name,Regional indicator,Happiness score,Whisker-high,Whisker-low,Dystopia + residual,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,2022,1,Finland,Western Europe,7.821,7.886,7.756,2.518,1.892,1.258,0.775,0.736,0.109,0.534
1,2022,2,Denmark,Western Europe,7.636,7.710,7.563,2.226,1.953,1.243,0.777,0.719,0.188,0.532
2,2022,3,Iceland,Western Europe,7.557,7.651,7.464,2.320,1.936,1.320,0.803,0.718,0.270,0.191
3,2022,4,Switzerland,Western Europe,7.512,7.586,7.437,2.153,2.026,1.226,0.822,0.677,0.147,0.461
4,2022,5,Netherlands,Western Europe,7.415,7.471,7.359,2.137,1.945,1.206,0.787,0.651,0.271,0.419
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,2022,139,Tanzania,Sub-Saharan Africa,3.702,3.847,3.558,0.735,0.848,0.597,0.425,0.578,0.248,0.270
121,2022,140,Sierra Leone,Sub-Saharan Africa,3.574,3.732,3.416,1.556,0.686,0.416,0.273,0.387,0.202,0.055
122,2022,144,Zimbabwe,Sub-Saharan Africa,2.995,3.110,2.880,0.548,0.947,0.690,0.270,0.329,0.106,0.105
123,2022,145,Lebanon,Middle East and North Africa,2.955,3.049,2.862,0.216,1.392,0.498,0.631,0.103,0.082,0.034
124,2022,146,Afghanistan,South Asia,2.404,2.469,2.339,1.263,0.758,0.000,0.289,0.000,0.089,0.005

In [24]:
new2022.columns

Index(['Year', 'RANK', 'Country name', 'Regional indicator', 'Happiness score',
       'Whisker-high', 'Whisker-low', 'Dystopia + residual',
       'Log GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

## working on 2021 dataset

In [25]:
#check NaN
y21.isnull().sum()

Country name                                  0
Regional indicator                            0
Ladder score                                  0
Standard error of ladder score                0
upperwhisker                                  0
lowerwhisker                                  0
Logged GDP per capita                         0
Social support                                0
Healthy life expectancy                       0
Freedom to make life choices                  0
Generosity                                    0
Perceptions of corruption                     0
Ladder score in Dystopia                      0
Explained by: Log GDP per capita              0
Explained by: Social support                  0
Explained by: Healthy life expectancy         0
Explained by: Freedom to make life choices    0
Explained by: Generosity                      0
Explained by: Perceptions of corruption       0
Dystopia + residual                           0
dtype: int64

In [26]:
#check the colums name of 2022
y22.columns

Index(['Year', 'RANK', 'Country name', 'Regional indicator', 'Happiness score',
       'Whisker-high', 'Whisker-low', 'Dystopia + residual',
       'Log GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

In [27]:
#check the colums name of 2021
y21.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

In [28]:
#drop the colums to match with 2022 file
y21 = y21.drop(['Standard error of ladder score','Logged GDP per capita', 'Social support', 'Healthy life expectancy','Freedom to make life choices', 'Generosity','Perceptions of corruption', 'Ladder score in Dystopia'], axis=1)
y21.head()

,Country name,Regional indicator,Ladder score,upperwhisker,lowerwhisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,7.904,7.780,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,7.687,7.552,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,7.643,7.500,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,7.670,7.438,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,7.518,7.410,1.501,1.079,0.753,0.647,0.302,0.384,2.798

In [29]:
#change the colums name to match with 2022 file
y21 = y21.rename(columns={'Ladder score': 'Happiness score','upperwhisker':'Whisker-high','lowerwhisker':'Whisker-low','Explained by: Log GDP per capita':'Log GDP per capita', 'Explained by: Social support':'Social support',
       'Explained by: Healthy life expectancy':'Healthy life expectancy',
       'Explained by: Freedom to make life choices':'Freedom to make life choices',
       'Explained by: Generosity':'Generosity', 'Explained by: Perceptions of corruption': 'Perceptions of corruption' })
y21

,Country name,Regional indicator,Happiness score,Whisker-high,Whisker-low,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,7.904,7.780,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,7.687,7.552,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,7.643,7.500,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,7.670,7.438,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,7.518,7.410,1.501,1.079,0.753,0.647,0.302,0.384,2.798
...,...,...,...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,3.512,3.748,3.276,0.451,0.731,0.007,0.405,0.103,0.015,1.800
145,Botswana,Sub-Saharan Africa,3.467,3.611,3.322,1.099,0.724,0.340,0.539,0.027,0.088,0.648
146,Rwanda,Sub-Saharan Africa,3.415,3.548,3.282,0.364,0.202,0.407,0.627,0.227,0.493,1.095
147,Zimbabwe,Sub-Saharan Africa,3.145,3.259,3.030,0.457,0.649,0.243,0.359,0.157,0.075,1.205
148,Afghanistan,South Asia,2.523,2.596,2.449,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [30]:
# Add Year colums to be easy to diffirentciate after marging the flies
y21.insert(loc=0, column='Year', value=2021)
y21

,Year,Country name,Regional indicator,Happiness score,Whisker-high,Whisker-low,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
0,2021,Finland,Western Europe,7.842,7.904,7.780,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,2021,Denmark,Western Europe,7.620,7.687,7.552,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,2021,Switzerland,Western Europe,7.571,7.643,7.500,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,2021,Iceland,Western Europe,7.554,7.670,7.438,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,2021,Netherlands,Western Europe,7.464,7.518,7.410,1.501,1.079,0.753,0.647,0.302,0.384,2.798
...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,2021,Lesotho,Sub-Saharan Africa,3.512,3.748,3.276,0.451,0.731,0.007,0.405,0.103,0.015,1.800
145,2021,Botswana,Sub-Saharan Africa,3.467,3.611,3.322,1.099,0.724,0.340,0.539,0.027,0.088,0.648
146,2021,Rwanda,Sub-Saharan Africa,3.415,3.548,3.282,0.364,0.202,0.407,0.627,0.227,0.493,1.095
147,2021,Zimbabwe,Sub-Saharan Africa,3.145,3.259,3.030,0.457,0.649,0.243,0.359,0.157,0.075,1.205
148,2021,Afghanistan,South Asia,2.523,2.596,2.449,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [31]:
# Create Rank Colums 
y21.insert(loc=1, column='RANK', value=range(1, 150))
y21

,Year,RANK,Country name,Regional indicator,Happiness score,Whisker-high,Whisker-low,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
0,2021,1,Finland,Western Europe,7.842,7.904,7.780,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,2021,2,Denmark,Western Europe,7.620,7.687,7.552,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,2021,3,Switzerland,Western Europe,7.571,7.643,7.500,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,2021,4,Iceland,Western Europe,7.554,7.670,7.438,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,2021,5,Netherlands,Western Europe,7.464,7.518,7.410,1.501,1.079,0.753,0.647,0.302,0.384,2.798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,2021,145,Lesotho,Sub-Saharan Africa,3.512,3.748,3.276,0.451,0.731,0.007,0.405,0.103,0.015,1.800
145,2021,146,Botswana,Sub-Saharan Africa,3.467,3.611,3.322,1.099,0.724,0.340,0.539,0.027,0.088,0.648
146,2021,147,Rwanda,Sub-Saharan Africa,3.415,3.548,3.282,0.364,0.202,0.407,0.627,0.227,0.493,1.095
147,2021,148,Zimbabwe,Sub-Saharan Africa,3.145,3.259,3.030,0.457,0.649,0.243,0.359,0.157,0.075,1.205
148,2021,149,Afghanistan,South Asia,2.523,2.596,2.449,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [32]:
# saving a new 2021 dataframe to csv 
y21.to_csv('new2021.csv',index=False)

In [33]:
# Read saved file and to cheack 
new2021 = pd.read_csv('new2021.csv')
new2021

,Year,RANK,Country name,Regional indicator,Happiness score,Whisker-high,Whisker-low,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
0,2021,1,Finland,Western Europe,7.842,7.904,7.780,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,2021,2,Denmark,Western Europe,7.620,7.687,7.552,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,2021,3,Switzerland,Western Europe,7.571,7.643,7.500,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,2021,4,Iceland,Western Europe,7.554,7.670,7.438,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,2021,5,Netherlands,Western Europe,7.464,7.518,7.410,1.501,1.079,0.753,0.647,0.302,0.384,2.798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,2021,145,Lesotho,Sub-Saharan Africa,3.512,3.748,3.276,0.451,0.731,0.007,0.405,0.103,0.015,1.800
145,2021,146,Botswana,Sub-Saharan Africa,3.467,3.611,3.322,1.099,0.724,0.340,0.539,0.027,0.088,0.648
146,2021,147,Rwanda,Sub-Saharan Africa,3.415,3.548,3.282,0.364,0.202,0.407,0.627,0.227,0.493,1.095
147,2021,148,Zimbabwe,Sub-Saharan Africa,3.145,3.259,3.030,0.457,0.649,0.243,0.359,0.157,0.075,1.205
148,2021,149,Afghanistan,South Asia,2.523,2.596,2.449,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [34]:
new2021.columns

Index(['Year', 'RANK', 'Country name', 'Regional indicator', 'Happiness score',
       'Whisker-high', 'Whisker-low', 'Log GDP per capita', 'Social support',
       'Healthy life expectancy', 'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Dystopia + residual'],
      dtype='object')

## working on 2020 dataset

In [35]:
#check NaN
y20.isnull().sum()

Country name                                  0
Regional indicator                            0
Ladder score                                  0
Standard error of ladder score                0
upperwhisker                                  0
lowerwhisker                                  0
Logged GDP per capita                         0
Social support                                0
Healthy life expectancy                       0
Freedom to make life choices                  0
Generosity                                    0
Perceptions of corruption                     0
Ladder score in Dystopia                      0
Explained by: Log GDP per capita              0
Explained by: Social support                  0
Explained by: Healthy life expectancy         0
Explained by: Freedom to make life choices    0
Explained by: Generosity                      0
Explained by: Perceptions of corruption       0
Dystopia + residual                           0
dtype: int64

In [36]:
#check the colums name of 2020
y20.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

In [37]:
#drop the colums to match with 2022 file
y20 = y20.drop(['Standard error of ladder score','Logged GDP per capita', 'Social support', 'Healthy life expectancy','Freedom to make life choices', 'Generosity','Perceptions of corruption', 'Ladder score in Dystopia'], axis=1)
y20.head()

,Country name,Regional indicator,Ladder score,upperwhisker,lowerwhisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,7.869766,7.747634,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,7.711245,7.579955,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,7.628528,7.491272,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,7.621347,7.387653,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,7.556281,7.419719,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266

In [38]:
#change the colums name to match with 2022 file
y20 = y20.rename(columns={'Ladder score': 'Happiness score','upperwhisker':'Whisker-high','lowerwhisker':'Whisker-low','Explained by: Log GDP per capita':'Log GDP per capita', 'Explained by: Social support':'Social support',
       'Explained by: Healthy life expectancy':'Healthy life expectancy',
       'Explained by: Freedom to make life choices':'Freedom to make life choices',
       'Explained by: Generosity':'Generosity', 'Explained by: Perceptions of corruption': 'Perceptions of corruption' })
y20

,Country name,Regional indicator,Happiness score,Whisker-high,Whisker-low,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,7.869766,7.747634,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,7.711245,7.579955,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,7.628528,7.491272,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,7.621347,7.387653,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,7.556281,7.419719,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266
...,...,...,...,...,...,...,...,...,...,...,...,...
148,Central African Republic,Sub-Saharan Africa,3.4759,3.701658,3.250141,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,2.860198
149,Rwanda,Sub-Saharan Africa,3.3123,3.415053,3.209547,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,0.548445
150,Zimbabwe,Sub-Saharan Africa,3.2992,3.414202,3.184198,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,0.841031
151,South Sudan,Sub-Saharan Africa,2.8166,3.027516,2.605684,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,1.378751
152,Afghanistan,South Asia,2.5669,2.628270,2.505530,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,1.507236

In [39]:
# Add Year colums to be easy to diffirentciate after marging the flies
y20.insert(loc=0, column='Year', value=2020)
y20

,Year,Country name,Regional indicator,Happiness score,Whisker-high,Whisker-low,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
0,2020,Finland,Western Europe,7.8087,7.869766,7.747634,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,2020,Denmark,Western Europe,7.6456,7.711245,7.579955,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,2020,Switzerland,Western Europe,7.5599,7.628528,7.491272,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,2020,Iceland,Western Europe,7.5045,7.621347,7.387653,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,2020,Norway,Western Europe,7.4880,7.556281,7.419719,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,2020,Central African Republic,Sub-Saharan Africa,3.4759,3.701658,3.250141,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,2.860198
149,2020,Rwanda,Sub-Saharan Africa,3.3123,3.415053,3.209547,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,0.548445
150,2020,Zimbabwe,Sub-Saharan Africa,3.2992,3.414202,3.184198,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,0.841031
151,2020,South Sudan,Sub-Saharan Africa,2.8166,3.027516,2.605684,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,1.378751
152,2020,Afghanistan,South Asia,2.5669,2.628270,2.505530,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,1.507236

In [40]:
# Create Rank Colums 
y20.insert(loc=1, column='RANK', value=range(1, 154))
y20

,Year,RANK,Country name,Regional indicator,Happiness score,Whisker-high,Whisker-low,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
0,2020,1,Finland,Western Europe,7.8087,7.869766,7.747634,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,2020,2,Denmark,Western Europe,7.6456,7.711245,7.579955,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,2020,3,Switzerland,Western Europe,7.5599,7.628528,7.491272,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,2020,4,Iceland,Western Europe,7.5045,7.621347,7.387653,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,2020,5,Norway,Western Europe,7.4880,7.556281,7.419719,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,2020,149,Central African Republic,Sub-Saharan Africa,3.4759,3.701658,3.250141,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,2.860198
149,2020,150,Rwanda,Sub-Saharan Africa,3.3123,3.415053,3.209547,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,0.548445
150,2020,151,Zimbabwe,Sub-Saharan Africa,3.2992,3.414202,3.184198,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,0.841031
151,2020,152,South Sudan,Sub-Saharan Africa,2.8166,3.027516,2.605684,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,1.378751
152,2020,153,Afghanistan,South Asia,2.5669,2.628270,2.505530,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,1.507236

In [41]:
# saving a new 2020 dataframe to csv 
y20.to_csv('new2020.csv',index=False)

In [42]:
# Read saved file and to cheack 
new2020 = pd.read_csv('new2020.csv')
new2020

,Year,RANK,Country name,Regional indicator,Happiness score,Whisker-high,Whisker-low,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
0,2020,1,Finland,Western Europe,7.8087,7.869766,7.747634,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,2020,2,Denmark,Western Europe,7.6456,7.711245,7.579955,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,2020,3,Switzerland,Western Europe,7.5599,7.628528,7.491272,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,2020,4,Iceland,Western Europe,7.5045,7.621347,7.387653,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,2020,5,Norway,Western Europe,7.4880,7.556281,7.419719,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,2020,149,Central African Republic,Sub-Saharan Africa,3.4759,3.701658,3.250141,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,2.860198
149,2020,150,Rwanda,Sub-Saharan Africa,3.3123,3.415053,3.209547,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,0.548445
150,2020,151,Zimbabwe,Sub-Saharan Africa,3.2992,3.414202,3.184198,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,0.841031
151,2020,152,South Sudan,Sub-Saharan Africa,2.8166,3.027516,2.605684,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,1.378751
152,2020,153,Afghanistan,South Asia,2.5669,2.628270,2.505530,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,1.507236

In [43]:
new2020.columns

Index(['Year', 'RANK', 'Country name', 'Regional indicator', 'Happiness score',
       'Whisker-high', 'Whisker-low', 'Log GDP per capita', 'Social support',
       'Healthy life expectancy', 'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Dystopia + residual'],
      dtype='object')

## Merging the 3 files

In [44]:
# merge the dataframes vertically using the concat method
merged_df = pd.concat([new2020, new2021,new2022])

# save the merged dataframe to a new CSV file
merged_df.to_csv('Worldhappinessreport2020-2022.csv', index=False)

In [45]:
# Read saved file and to cheack 
newreport = pd.read_csv('Worldhappinessreport2020-2022.csv')
newreport

,Year,RANK,Country name,Regional indicator,Happiness score,Whisker-high,Whisker-low,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
0,2020,1,Finland,Western Europe,7.8087,7.869766,7.747634,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,2020,2,Denmark,Western Europe,7.6456,7.711245,7.579955,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,2020,3,Switzerland,Western Europe,7.5599,7.628528,7.491272,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,2020,4,Iceland,Western Europe,7.5045,7.621347,7.387653,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,2020,5,Norway,Western Europe,7.4880,7.556281,7.419719,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,2022,139,Tanzania,Sub-Saharan Africa,3.7020,3.847000,3.558000,0.848000,0.597000,0.425000,0.578000,0.248000,0.270000,0.735000
423,2022,140,Sierra Leone,Sub-Saharan Africa,3.5740,3.732000,3.416000,0.686000,0.416000,0.273000,0.387000,0.202000,0.055000,1.556000
424,2022,144,Zimbabwe,Sub-Saharan Africa,2.9950,3.110000,2.880000,0.947000,0.690000,0.270000,0.329000,0.106000,0.105000,0.548000
425,2022,145,Lebanon,Middle East and North Africa,2.9550,3.049000,2.862000,1.392000,0.498000,0.631000,0.103000,0.082000,0.034000,0.216000
426,2022,146,Afghanistan,South Asia,2.4040,2.469000,2.339000,0.758000,0.000000,0.289000,0.000000,0.089000,0.005000,1.263000

In [46]:
#check NaN values
newreport.isnull().sum()

Year                            0
RANK                            0
Country name                    0
Regional indicator              0
Happiness score                 0
Whisker-high                    0
Whisker-low                     0
Log GDP per capita              0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
Dystopia + residual             0
dtype: int64

In [47]:
newreport.columns

Index(['Year', 'RANK', 'Country name', 'Regional indicator', 'Happiness score',
       'Whisker-high', 'Whisker-low', 'Log GDP per capita', 'Social support',
       'Healthy life expectancy', 'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Dystopia + residual'],
      dtype='object')